#!/usr/bin/env python

__author__ = "Doug Woos"


"""
Outputs the unicode Christmas tree glyph (1F384) if the current date
is between Dec. 1 and Dec. 25, inclusive. Throw it into your prompt,
e.g. (in zsh)

PROMPT='$(christmas-tree)  '

Note: for this to work correctly, you've got to set Python's default
encoding to utf-8 and have a UTF8 capable terminal. To do the former,
put the following lines in your sitecustomize.py file
(/Library/Python/2.7/site-packages/sitecustomize.py on OS X):

import sys
sys.setdefaultencoding('utf-8')
"""

import sys
from datetime import datetime

n = datetime.now()

if n.month == 12 and n.day <= 25:
    print u'\U0001F384'
