#!/usr/bin/env zsh
# Author: Doug Woos, Dougal Sutherland

# Outputs the unicode Christmas tree glyph (1F384) if the current date
# is between Dec. 1 and Dec. 25, inclusive. Throw it into your prompt,
# e.g. (in zsh)
# 
# source $HOME/.christmas-tree
# PROMPT='$(christmas-tree)'

function christmas-tree () {
    d=$(date '+%-m %d'); # eg '12 01'; space because otherwise date complains
    d=${d/[[:space:]]/.}; # eg '12.01', '12.25'
    if [[ $d -ge 12.01 && $d -le 12.25 ]]; then
        echo -e '\U0001F384 '
    fi
}
